version: '3.8'

services:
  db:   # This is the name of your service
    image: postgres:latest
    environment:
      POSTGRES_USER: postgres       # Username for the database
      POSTGRES_PASSWORD: postgres   # Password for the database
      POSTGRES_DB: inventory-management-db  # Database name
    ports:
      - "5432:5432"  # Expose PostgreSQL port
    volumes:
      - pgdata:/var/lib/postgresql/data  # Persist data across container restarts

volumes:
  pgdata:  # Named volume to persist data
